name: foliate-ai
grade: stable
adopt-info: foliate.ai
license: GPL-3.0+
contact: https://github.com/stonega/foliate.ai
base: core24
confinement: strict
compression: lzo
platforms:
  amd64:
  arm64:
  armhf:
layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET/webkitgtk-6.0:
    bind: $SNAP/webkitgtk-platform/usr/lib/$CRAFT_ARCH_TRIPLET/webkitgtk-6.0
slots:
  foliate.ai:
    interface: dbus
    bus: session
    name: io.github.stonega.foliate
plugs:
  webkitgtk-6-gnome-2404:
    interface: content
    target: $SNAP/webkitgtk-platform
    default-provider: webkitgtk-6-gnome-2404
apps:
  foliate-ai:
    command: usr/bin/foliate-ai
    extensions:
      - gnome
    plugs:
      - home
      - removable-media
      - network
      - network-status
      - unity7
      - audio-playback
    desktop: usr/share/applications/io.github.stonega.foliate.desktop
    common-id: io.github.stonega.foliate
    environment:
      SPEECHD_ADDRESS: "unix_socket:/run/user/$SNAP_UID/speech-dispatcher/speechd.sock"
      LD_LIBRARY_PATH: $SNAP/webkitgtk-platform/usr/lib:$SNAP/webkitgtk-platform/usr/lib/$CRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH
      GI_TYPELIB_PATH: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0:$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/gjs/girepository-1.0:$SNAP/webkitgtk-platform/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0
parts:
  foliate.ai:
    plugin: meson
    source: .
    source-type: local
    build-environment:
      - PKG_CONFIG_PATH: /snap/webkitgtk-6-gnome-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:$PKG_CONFIG_PATH
    meson-parameters:
      - --prefix=/snap/foliate.ai/current/usr
    override-pull: |
      craftctl default
      # Workaround for snapcraft not copying submodules in local source
      if [ ! -f src/foliate-js/comic-book.js ]; then
        rm -rf src/foliate-js
        git clone https://github.com/johnfactotum/foliate-js src/foliate-js
      fi
      sed -i '1c#!/snap/foliate/current/gnome-platform/usr/bin/gjs -m' src/main.js
    build-packages:
      - git
      - xmlstarlet
    build-snaps:
      - webkitgtk-6-gnome-2404-sdk/latest/stable
    parse-info:
      - usr/share/metainfo/io.github.stonega.foliate.metainfo.xml
    organize:
      snap/foliate.ai/current/usr: usr
  deps:
    plugin: nil
    stage-packages:
      - libspeechd2 # probably necessary, need testing
    prime:
      - usr/lib/*/libspeechd.so.*

